server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          default-label: auth-jwt
          uri: https://github.com/cavanosa/microservices-tutorial
          search-paths: config-data
  application:
    name: config-service
